# Generated by Django 2.0 on 2018-01-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['currency__name'], 'verbose_name': 'Currency Account', 'verbose_name_plural': 'Currencies Accounts'},
        ),
    ]
