# Generated by Django 2.0.1 on 2018-02-03 00:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_core', '0009_auto_20180130_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrencies',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', to='exchange_core.Currencies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='exchange_orderbook.BaseCurrencies')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='exchange_core.Currencies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('unit', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('type', models.CharField(choices=[('b', 'b'), ('s', 's')], max_length=1)),
                ('status', models.CharField(choices=[('created', 'created'), ('executed', 'executed')], default='created', max_length=1)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.Markets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
