# Generated by Django 2.1.1 on 2018-09-19 15:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrencies',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=100, help_text='The order who base currency must appears in Orderbook', verbose_name='Order')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', to='exchange_core.Currencies', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Base currency',
                'verbose_name_plural': 'Base currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPairs',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min price')),
                ('max_price', models.DecimalField(decimal_places=8, default=Decimal('1000000.00'), max_digits=20, verbose_name='Max price')),
                ('min_qty', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min quantity')),
                ('max_qty', models.DecimalField(decimal_places=8, default=Decimal('1000000.00'), max_digits=20, verbose_name='Max quantity')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='exchange_orderbook.BaseCurrencies', verbose_name='Base currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='exchange_core.Currencies', verbose_name='Quote currency')),
            ],
            options={
                'verbose_name': 'Currency pair',
                'verbose_name_plural': 'Currency pairs',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Price')),
                ('qty', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Quantity')),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20, null=True, verbose_name='Fee')),
                ('side', models.CharField(choices=[('bid', 'Bid'), ('ask', 'Ask')], max_length=1, verbose_name='Side')),
                ('state', models.CharField(choices=[('created', 'Created'), ('executed', 'Executed'), ('canceled', 'Canceled')], default='created', max_length=30, verbose_name='State')),
                ('executed', models.DateTimeField(null=True, verbose_name='Executed')),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.CurrencyPairs', verbose_name='Currency pair')),
                ('fee_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_core.Currencies', verbose_name='Fee currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taker_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('maker_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('maker_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maker_orders', to='exchange_orderbook.Orders')),
                ('taker_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taker_orders', to='exchange_orderbook.Orders')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
    ]
