# Generated by Django 2.1.1 on 2018-09-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='side',
            field=models.CharField(choices=[('bid', 'Bid'), ('ask', 'Ask')], max_length=3, verbose_name='Side'),
        ),
    ]
