# Generated by Django 2.1 on 2018-10-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0002_auto_20180921_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('bid_ask', 'Bid/Ask'), ('market', 'To market')], default='bid_ask', max_length=30, verbose_name='Type'),
        ),
    ]
