# Generated by Django 2.0.1 on 2018-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0002_auto_20180203_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='unit',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('executed', 'executed')], default='created', max_length=30),
        ),
    ]
