# Generated by Django 2.0.1 on 2018-02-05 10:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0003_auto_20180204_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('passive_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('active_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_orders', to='exchange_orderbook.Orders')),
                ('passive_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_orders', to='exchange_orderbook.Orders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
