# Generated by Django 2.0.2 on 2018-02-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0004_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='active_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_orders', to='exchange_orderbook.Orders'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='passive_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passive_orders', to='exchange_orderbook.Orders'),
        ),
    ]
