# Generated by Django 2.0.2 on 2018-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0005_auto_20180218_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('executed', 'executed'), ('canceled', 'canceled')], default='created', max_length=30),
        ),
    ]
