# Generated by Django 2.0.1 on 2018-03-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0006_auto_20180301_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecurrencies',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
