# Generated by Django 2.0.1 on 2018-05-17 17:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0008_auto_20180329_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('open', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc', to='exchange_orderbook.Markets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
