# Generated by Django 2.1 on 2018-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0010_auto_20180831_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fee',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
