# Generated by Django 2.1 on 2018-09-01 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0003_auto_20180901_1752'),
        ('exchange_orderbook', '0011_orders_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_core.Currencies'),
        ),
        migrations.AddField(
            model_name='orders',
            name='executed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
