# Generated by Django 2.1.1 on 2018-09-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0012_auto_20180901_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecurrencies',
            options={'verbose_name': 'Market', 'verbose_name_plural': 'Markets'},
        ),
        migrations.AlterModelOptions(
            name='markets',
            options={'verbose_name': 'Pair', 'verbose_name_plural': 'Pairs'},
        ),
        migrations.AlterModelOptions(
            name='matchs',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='currency',
        ),
        migrations.AlterField(
            model_name='orders',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.Markets', verbose_name='Pair'),
        ),
    ]
