# Generated by Django 2.1.1 on 2018-09-14 21:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0003_auto_20180901_1752'),
        ('exchange_orderbook', '0014_orders_fee_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='markets',
            new_name='currencypairs',
        ),
        migrations.RenameField(
            model_name='currencypairs',
            old_name='currency',
            new_name='quote_currency',
        ),
        migrations.AlterModelOptions(
            name='basecurrencies',
            options={'verbose_name': 'Currency Pair', 'verbose_name_plural': 'Currency Pairs'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='matchs',
            old_name='active_fee',
            new_name='maker_fee',
        ),
        migrations.RenameField(
            model_name='matchs',
            old_name='passive_order',
            new_name='maker_order',
        ),
        migrations.RenameField(
            model_name='matchs',
            old_name='passive_fee',
            new_name='taker_fee',
        ),
        migrations.RenameField(
            model_name='matchs',
            old_name='active_order',
            new_name='taker_order',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='market',
            new_name='currency_pair',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='type',
            new_name='side',
        ),
        migrations.AlterField(
            model_name='orders',
            name='side',
            field=models.CharField(choices=[('bid', 'Bid'), ('ask', 'Ask')], max_length=1, null=True),
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('executed', 'Executed'), ('canceled', 'Canceled')], default='created', max_length=30),
        ),
        migrations.DeleteModel(
            name='ohlc'
        ),
    ]
