# Generated by Django 2.1.1 on 2018-09-14 22:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0015_auto_20180914_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taker_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('maker_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='maker_order',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='taker_order',
        ),
        migrations.AlterField(
            model_name='currencypairs',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='exchange_orderbook.BaseCurrencies'),
        ),
        migrations.AlterField(
            model_name='currencypairs',
            name='quote_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='exchange_core.Currencies'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.CurrencyPairs', verbose_name='Currency Pair'),
        ),
        migrations.DeleteModel(
            name='Matchs',
        ),
        migrations.AddField(
            model_name='trades',
            name='maker_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maker_orders', to='exchange_orderbook.Orders'),
        ),
        migrations.AddField(
            model_name='trades',
            name='taker_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taker_orders', to='exchange_orderbook.Orders'),
        ),
    ]
