# Generated by Django 2.1.1 on 2018-09-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0016_auto_20180914_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='executed_at',
            new_name='executed',
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.CurrencyPairs', verbose_name='Currency Pair'),
        ),
    ]
