# Generated by Django 2.1.1 on 2018-09-16 02:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0017_auto_20180914_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypairs',
            name='max_qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000000.00'), max_digits=20, verbose_name='Max quantity'),
        ),
        migrations.AddField(
            model_name='currencypairs',
            name='min_qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min quantity'),
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='basecurrencies',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', to='exchange_core.Currencies', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='basecurrencies',
            name='order',
            field=models.IntegerField(default=100, help_text='The order who base currency must appears in Orderbook', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='currencypairs',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='exchange_orderbook.BaseCurrencies', verbose_name='Base currency'),
        ),
        migrations.AlterField(
            model_name='currencypairs',
            name='max_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000000.00'), max_digits=20, verbose_name='Max price'),
        ),
        migrations.AlterField(
            model_name='currencypairs',
            name='min_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min price'),
        ),
        migrations.AlterField(
            model_name='currencypairs',
            name='quote_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='exchange_core.Currencies', verbose_name='Quote currency'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.CurrencyPairs', verbose_name='Currency Pair'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='executed',
            field=models.DateTimeField(null=True, verbose_name='Executed date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fee',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fee_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_core.Currencies', verbose_name='Fee currency'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='side',
            field=models.CharField(choices=[('bid', 'Bid'), ('ask', 'Ask')], max_length=1, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('executed', 'Executed'), ('canceled', 'Canceled')], default='created', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
