# Generated by Django 2.1.1 on 2018-09-17 19:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0018_auto_20180916_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecurrencies',
            options={'verbose_name': 'Base currency', 'verbose_name_plural': 'Base currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencypairs',
            options={'verbose_name': 'Currency pair', 'verbose_name_plural': 'Currency pairs'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.CurrencyPairs', verbose_name='Currency pair'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='executed',
            field=models.DateTimeField(null=True, verbose_name='Executed'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Quantity'),
        ),
    ]
