# Generated by Django 2.1.1 on 2018-09-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_orderbook', '0021_auto_20180917_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_orderbook.CurrencyPairs', verbose_name='Currency pair'),
        ),
    ]
